package info.freelibrary.iiif.presentation.properties;

import java.net.URI;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import info.freelibrary.iiif.presentation.utils.Constants;

/**
 * A web page that is about the object represented by the resource that has the <code>homepage</code> property. The web
 * page is usually published by the organization responsible for the object, and might be generated by a content
 * management system or other cataloging system.
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonPropertyOrder({ Constants.ID, Constants.TYPE, Constants.LABEL, Constants.FORMAT })
public class Homepage extends Localized<Homepage> {

    @JsonProperty(Constants.ID)
    private final URI myID;

    @JsonProperty(Constants.TYPE)
    private final String myType;

    @JsonProperty(Constants.LABEL)
    private final Label myLabel;

    @JsonProperty(Constants.FORMAT)
    private String myFormat;

    /**
     * Creates a IIIF presentation homepage.
     *
     * @param aID A homepage ID
     * @param aType A homepage type
     * @param aLabel A homepage label
     */
    public Homepage(final URI aID, final String aType, final Label aLabel) {
        myID = aID;
        myType = aType;
        myLabel = aLabel;
    }

    /**
     * Creates a IIIF presentation homepage.
     *
     * @param aID A homepage ID in string form
     * @param aType A homepage type
     * @param aLabel A homepage label in string form
     */
    public Homepage(final String aID, final String aType, final String aLabel) {
        this(URI.create(aID), aType, new Label(aLabel));
    }

    /**
     * Gets the ID.
     *
     * @return The ID
     */
    public URI getID() {
        return myID;
    }

    /**
     * Gets the type.
     *
     * @return The type
     */
    public String getType() {
        return myType;
    }

    /**
     * Gets the label.
     *
     * @return The label
     */
    public Label getLabel() {
        return myLabel;
    }

    /**
     * Gets the format.
     *
     * @return The format
     */
    public String getFormat() {
        return myFormat;
    }

    /**
     * Sets the format.
     *
     * @param aFormat The format of the homepage
     * @return The homepage
     */
    public Homepage setFormat(final String aFormat) {
        myFormat = aFormat;
        return this;
    }
}
