
package info.freelibrary.iiif.presentation.properties;

import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.google.common.net.MediaType;

import info.freelibrary.iiif.presentation.Constants;

import io.vertx.core.json.Json;
import io.vertx.core.json.JsonObject;

/**
 * A web page that is about the object represented by the resource that has the <code>homepage</code> property. The
 * web page is usually published by the organization responsible for the object, and might be generated by a content
 * management system or other cataloging system.
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonPropertyOrder({ Constants.ID, Constants.TYPE, Constants.LABEL, Constants.FORMAT, Constants.LANGUAGE })
public class Homepage extends AbstractLinkProperty<Homepage> implements Localized<Homepage> {

    private List<String> myLanguages;

    /**
     * Creates a IIIF presentation homepage.
     *
     * @param aID A homepage ID
     * @param aType A homepage type
     * @param aLabel A homepage label
     */
    public Homepage(final URI aID, final String aType, final Label aLabel) {
        super(aID, aType, aLabel);
    }

    /**
     * Creates a IIIF presentation homepage.
     *
     * @param aID A homepage ID in string form
     * @param aType A homepage type
     * @param aLabel A homepage label in string form
     */
    public Homepage(final String aID, final String aType, final String aLabel) {
        super(URI.create(aID), aType, new Label(aLabel));
    }

    /**
     * Creates a homepage for Jackson's deserialization process.
     */
    @SuppressWarnings("unused")
    private Homepage() {
    }

    @Override
    public Homepage setID(final URI aID) {
        return (Homepage) super.setID(aID);
    }

    /**
     * Sets the ID from the supplied string.
     *
     * @param aID The ID of the homepage in string form
     * @return The homepage
     */
    @JsonIgnore
    public Homepage setID(final String aID) {
        return (Homepage) super.setID(URI.create(aID));
    }

    @Override
    public Homepage setType(final String aType) {
        return (Homepage) super.setType(aType);
    }

    /**
     * Gets the label.
     *
     * @return The label
     */
    public Label getLabel() {
        return super.getNullableLabel();
    }

    @Override
    public Homepage setLabel(final Label aLabel) {
        return (Homepage) super.setLabel(aLabel);
    }

    @Override
    @JsonIgnore
    public Homepage setLabel(final String aLabel) {
        return (Homepage) super.setLabel(new Label(aLabel));
    }

    @Override
    @JsonIgnore
    public Optional<MediaType> getFormatMediaType() {
        return super.getFormatMediaType();
    }

    @Override
    public Optional<String> getFormat() {
        return super.getFormat();
    }

    @Override
    @JsonIgnore
    public Homepage setFormat(final MediaType aMediaType) {
        return (Homepage) super.setFormat(aMediaType);
    }

    @Override
    public Homepage setFormat(final String aFormat) {
        return (Homepage) super.setFormat(aFormat);
    }

    /**
     * Gets the resource's languages.
     *
     * @return A list of the resource's languages
     */
    @Override
    @JsonGetter(Constants.LANGUAGE)
    public List<String> getLanguages() {
        if (myLanguages == null) {
            myLanguages = new ArrayList<>();
        }

        return myLanguages;
    }

    @Override
    public Homepage setLanguages(final String... aLangArray) {
        return (Homepage) Localized.super.setLanguages(aLangArray);
    }

    @Override
    public int hashCode() {
        return 31 * super.hashCode() + Objects.hash(getLanguages());
    }

    @Override
    public boolean equals(final Object aObject) {
        if (!super.equals(aObject)) {
            return false;
        }

        if (getClass() != aObject.getClass()) {
            return false;
        }

        return getLanguages().equals(((Homepage) aObject).getLanguages());
    }

    /**
     * Returns a JsonObject of this resource.
     *
     * @return A JsonObject of this resource
     */
    @Override
    public JsonObject toJSON() {
        return JsonObject.mapFrom(this);
    }

    /**
     * Returns a homepage from its JSON representation.
     *
     * @param aJsonObject A homepage in JSON form
     * @return This homepage
     */
    public static Homepage fromJSON(final JsonObject aJsonObject) {
        return Json.decodeValue(aJsonObject.toString(), Homepage.class);
    }

    /**
     * Returns a homepage from its JSON representation.
     *
     * @param aJsonString A homepage in string form
     * @return This homepage
     */
    public static Homepage fromString(final String aJsonString) {
        return fromJSON(new JsonObject(aJsonString));
    }
}
