
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "ksclarke"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "ksclarke"
  - package-ecosystem: "docker"
    directory: "/src/main/docker"
    schedule:
      interval: "weekly"
    assignees:
      - "ksclarke"
