<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <artifactId>jsh4jpv3</artifactId>
  <packaging>jar</packaging>
  <version>${revision}</version>

  <name>jsh4jpv3</name>
  <description>A JShell service to evaluate JPv3 scripts</description>
  <url>http://projects.freelibrary.info/jiiify-presentation</url>

  <licenses>
    <license>
      <name>Mozilla Public License 2.0 (MPL-2.0)</name>
      <url>https://opensource.org/licenses/MPL-2.0</url>
    </license>
  </licenses>

  <scm>
    <connection>scm:git:git@github.com:ksclarke/jiiify-presentation.git</connection>
    <developerConnection>scm:git:git@github.com:ksclarke/jiiify-presentation.git</developerConnection>
    <url>git@github.com:ksclarke/jiiify-presentation.git</url>
  </scm>

  <issueManagement>
    <system>GitHub</system>
    <url>https://github.com/ksclarke/jiiify-presentation/issues</url>
  </issueManagement>

  <developers>
    <developer>
      <id>ksclarke</id>
      <name>Kevin S. Clarke</name>
      <email>ksclarke@ksclarke.io</email>
      <timezone>America/New_York</timezone>
    </developer>
    <!-- Also https://github.com/ksclarke/jiiify-presentation/graphs/contributors -->
  </developers>

  <properties>
    <!-- Dependency versions -->
    <microhttp.version>0.11</microhttp.version>
    <jpv3.version>0.0.0-SNAPSHOT</jpv3.version>

    <!-- Configuring Sonar to use the right (i.e., webrepl) branch -->
    <sonar.branch.target>webrepl</sonar.branch.target>
    <sonar.projectKey>info.freelibrary:jiiify-presentation-v3</sonar.projectKey>

    <!-- Plugin related versions -->
    <docker.plugin.version>0.45.0</docker.plugin.version>
    <deploy.plugin.version>3.1.3</deploy.plugin.version>
    <maven.shade.version>3.6.0</maven.shade.version>

    <!-- Test dependency versions -->
    <junit.version>5.11.0</junit.version>

    <!-- Skip the requirement that none of the dependencies are snapshot versions -->
    <enforcer.skip>true</enforcer.skip>

    <!-- The default logging level for the server. -->
    <logLevel>ERROR</logLevel>

    <!-- Configure what our Docker image should be called (see `deploy` profile for more) -->
    <docker.namespace></docker.namespace>
    <docker.image.name>${docker.namespace}${project.artifactId}:${revision}</docker.image.name>

    <!-- Configuration for Docker attestations -->
    <docker.sbom>false</docker.sbom>
    <docker.provenance>false</docker.provenance>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.microhttp</groupId>
      <artifactId>microhttp</artifactId>
      <version>${microhttp.version}</version>
    </dependency>
    <dependency>
      <groupId>info.freelibrary</groupId>
      <artifactId>jiiify-presentation-v3</artifactId>
      <version>${jpv3.version}</version>
    </dependency>
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
    </dependency>

    <!-- Dependencies used for testing -->
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>${junit.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
        <filtering>true</filtering>
        <includes>
          <include>**/logback.xml</include>
        </includes>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>${maven.shade.version}</version>
        <executions>
          <execution>
            <id>uber-jar</id>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <createDependencyReducedPom>false</createDependencyReducedPom>
              <shadedArtifactAttached>true</shadedArtifactAttached>
              <shadedClassifierName>uber</shadedClassifierName>
              <filters>
                <filter>
                  <artifact>*:*</artifact>
                  <excludes>
                    <exclude>module-info.class</exclude>
                    <exclude>META-INF/*.SF</exclude>
                    <exclude>META-INF/*.DSA</exclude>
                    <exclude>META-INF/*.RSA</exclude>
                    <exclude>META-INF/NOTICE</exclude>
                    <exclude>META-INF/LICENSE</exclude>
                    <exclude>META-INF/LICENSE.txt</exclude>
                    <exclude>META-INF/MANIFEST.MF</exclude>
                    <exclude>META-INF/versions/9/module-info.class</exclude>
                  </excludes>
                </filter>
                <filter>
                  <artifact>info.freelibrary:jiiify-presentation-v3</artifact>
                  <excludes>
                    <exclude>info/freelibrary/iiif/presentation/v3/properties/MediaType.class</exclude>
                  </excludes>
                </filter>
              </filters>
              <transformers>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                  <mainClass>info.freelibrary.jsh4jvp3.Server</mainClass>
                </transformer>
              </transformers>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <artifactId>maven-javadoc-plugin</artifactId>
        <configuration>
          <skip>true</skip>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
      </plugin>

      <plugin>
        <artifactId>maven-pmd-plugin</artifactId>
      </plugin>

      <plugin>
        <artifactId>maven-checkstyle-plugin</artifactId>
      </plugin>

      <plugin>
        <artifactId>maven-enforcer-plugin</artifactId>
      </plugin>

      <plugin>
        <artifactId>maven-dependency-plugin</artifactId>
      </plugin>

      <plugin>
        <groupId>net.revelc.code.formatter</groupId>
        <artifactId>formatter-maven-plugin</artifactId>
      </plugin>

      <plugin>
        <artifactId>maven-resources-plugin</artifactId>
        <executions>
          <execution>
            <id>copy-web-resources</id>
            <phase>validate</phase>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <configuration>
              <outputDirectory>${basedir}/target/classes/webroot</outputDirectory>
              <resources>
                <resource>
                  <directory>${basedir}/src/main/webapp</directory>
                </resource>
              </resources>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <argLine>${jacoco.agent.arg}</argLine>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-failsafe-plugin</artifactId>
        <configuration>
          <systemPropertyVariables>
            <server.port>${test.http.port}</server.port>
          </systemPropertyVariables>
          <argLine>--add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED</argLine>
        </configuration>
      </plugin>

      <!-- Disable standard deploy; we publish a Docker image, not Jar file -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-deploy-plugin</artifactId>
        <version>${deploy.plugin.version}</version>
        <configuration>
          <skip>true</skip>
        </configuration>
      </plugin>

      <!-- Creates a Docker image and uses it for functional testing -->
      <plugin>
        <groupId>io.fabric8</groupId>
        <artifactId>docker-maven-plugin</artifactId>
        <version>${docker.plugin.version}</version>
        <configuration>
          <logStdout>true</logStdout>
          <verbose>true</verbose>
          <images>
            <image>
              <name>${docker.image.name}</name>
              <build>
                <dockerFile>${project.basedir}/src/main/docker/Dockerfile</dockerFile>
                <buildx>
                  <platforms>
                    <platform>linux/amd64</platform>
                    <platform>linux/arm64/v8</platform>
                  </platforms>
                  <!-- Multi-arch builds don't work on GA because containerd isn't supported (cf. reason number two on
                  https://github.com/fabric8io/docker-maven-plugin/issues/1557#issuecomment-1325203489) -->
                  <attestations>
                    <sbom>${docker.sbom}</sbom>
                    <provenance>${docker.provenance}</provenance>
                  </attestations>
                </buildx>
                <assembly>
                  <inline>
                    <fileSets>
                      <fileSet>
                        <!-- The directory where we can find our Maven-built artifact -->
                        <directory>${project.basedir}/target/</directory>
                        <!-- We don't want directory structure on output, just the artifact -->
                        <outputDirectory>.</outputDirectory>
                        <includes>
                          <include>${project.artifactId}-${project.version}-uber.jar</include>
                        </includes>
                      </fileSet>
                    </fileSets>
                  </inline>
                </assembly>
              </build>
              <run>
                <containerNamePattern>${project.artifactId}</containerNamePattern>
                <ports>
                  <port>${test.http.port}:8888</port>
                </ports>
                <!-- Test to make sure the server started as expected -->
                <wait>
                  <http>
                    <url>http://0.0.0.0:${test.http.port}/editor</url>
                    <method>GET</method>
                    <status>201</status>
                  </http>
                </wait>
              </run>
            </image>
          </images>
        </configuration>
        <executions>

          <!-- Builds the Docker image -->
          <execution>
            <id>docker-build</id>
            <phase>pre-integration-test</phase>
            <goals>
              <goal>build</goal>
            </goals>
          </execution>

          <!-- Creates and starts the Docker containers for integration testing -->
          <execution>
            <id>docker-start</id>
            <phase>pre-integration-test</phase>
            <goals>
              <goal>start</goal>
            </goals>
          </execution>

          <!-- Stops and removes the integration tests' Docker containers -->
          <execution>
            <id>docker-stop</id>
            <phase>post-integration-test</phase>
            <goals>
              <goal>stop</goal>
            </goals>
            <configuration>
              <allContainers>true</allContainers>
            </configuration>
          </execution>

          <!-- Deploys the application's Docker image -->
          
          <execution>
            <id>docker-deploy</id>
            <phase>deploy</phase>
            <goals>
              <goal>push</goal>
            </goals>
            <configuration>
              <authConfig>
                <username>${env.DOCKER_USERNAME}</username>
                <password>${env.DOCKER_PASSWORD}</password>
              </authConfig>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <!-- This profile is used when building on GitHub Actions -->
    <profile>
      <id>deploy</id>
      <activation>
        <property>
          <name>env.DOCKER_ACCOUNT</name>
        </property>
      </activation>
      <properties>
        <docker.namespace>${env.DOCKER_ACCOUNT}/</docker.namespace>
      </properties>
    </profile>
  </profiles>

  <!-- We adopt a lot of configurations from our parent project -->
  <parent>
    <artifactId>freelib-parent</artifactId>
    <groupId>info.freelibrary</groupId>
    <version>12.0.0</version>
  </parent>

</project>
