<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>jiiify-presentation-v3</artifactId>
    <packaging>jar</packaging>
    <version>${revision}</version>

    <name>jiiify-presentation</name>
    <description>A Java Library for version 3 of the IIIF Presentation API</description>
    <url>https://projects.freelibrary.info/jiiify-presentation-v3</url>

    <licenses>
        <license>
            <name>Mozilla Public License 2.0 (MPL-2.0)</name>
            <url>https://opensource.org/licenses/MPL-2.0</url>
        </license>
    </licenses>

    <scm>
        <connection>scm:git:git@github.com:ksclarke/jiiify-presentation.git</connection>
        <developerConnection>scm:git:git@github.com:ksclarke/jiiify-presentation.git</developerConnection>
        <url>git@github.com:ksclarke/jiiify-presentation.git</url>
    </scm>

    <issueManagement>
        <system>GitHub</system>
        <url>https://github.com/ksclarke/jiiify-presentation/issues</url>
    </issueManagement>

    <developers>
        <developer>
            <id>ksclarke</id>
            <name>Kevin S. Clarke</name>
            <email>ksclarke@ksclarke.io</email>
            <timezone>America/New_York</timezone>
        </developer>
        <!-- Also https://github.com/ksclarke/jiiify-presentation/graphs/contributors -->
    </developers>

    <properties>
        <revision>0.0.0-SNAPSHOT</revision>

        <!-- Application dependencies -->
        <jackson.version>2.21.1</jackson.version>
        <jackson.databind.version>2.21.1</jackson.databind.version>
        <jackson.annotations.version>2.21</jackson.annotations.version>
        <freelib.utils.version>5.3.2</freelib.utils.version>
        <jsoup.version>1.21.1</jsoup.version>
        <combinatorics.version>3.4.0</combinatorics.version>
        <media.fragments.uri.version>2.4</media.fragments.uri.version>

        <!-- Build-related dependencies -->
        <exec.plugin.version>3.5.0</exec.plugin.version>
        <native.maven.plugin.version>1.1.0</native.maven.plugin.version>

        <!-- Test-related dependencies -->
        <magicfree.json.version>0.11.0</magicfree.json.version>
        <system.lambda.version>1.2.1</system.lambda.version>
        <mockito.version>5.20.0</mockito.version>
        <opencsv.version>4.6</opencsv.version>
        <lorem.version>2.1</lorem.version>

        <!-- A property used by the build process -->
        <tag.prefix>v3</tag.prefix>

        <!-- The log level to use when testing -->
        <testLogLevel>WARN</testLogLevel>

        <!-- Mockito configuration properties -->
        <mockito.path>${settings.localRepository}/org/mockito/mockito-core/${mockito.version}</mockito.path>
        <mockito.agent.arg>-javaagent:${mockito.path}/mockito-core-${mockito.version}.jar</mockito.agent.arg>
    </properties>

    <dependencies>
        <dependency>
            <groupId>info.freelibrary</groupId>
            <artifactId>freelib-utils</artifactId>
            <version>${freelib.utils.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>${jackson.annotations.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.databind.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jdk8</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-csv</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jsoup</groupId>
            <artifactId>jsoup</artifactId>
            <version>${jsoup.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.tkurz</groupId>
            <artifactId>media-fragments-uri</artifactId>
            <version>${media.fragments.uri.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.dpaukov</groupId>
            <artifactId>combinatoricslib3</artifactId>
            <version>${combinatorics.version}</version>
        </dependency>

        <!-- The dependencies below are only used for testing -->
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>info.freelibrary</groupId>
            <artifactId>magicfree-json</artifactId>
            <version>${magicfree.json.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.thedeanda</groupId>
            <artifactId>lorem</artifactId>
            <version>${lorem.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.github.stefanbirkner</groupId>
            <artifactId>system-lambda</artifactId>
            <version>${system.lambda.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>${mockito.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <testResources>
            <testResource>
                <directory>src/test/resources</directory>
                <includes>
                    <include>logback-test.xml</include>
                </includes>
                <filtering>true</filtering>
            </testResource>
            <testResource>
                <directory>src/test/resources</directory>
                <excludes>
                    <exclude>logback-test.xml</exclude>
                </excludes>
                <filtering>false</filtering>
            </testResource>

            <!-- We can also override the default logging configuration with a file in our root project directory -->
            <testResource>
                <directory>${project.basedir}</directory>
                <includes>
                    <include>logback-test.xml</include>
                </includes>
                <filtering>true</filtering>
            </testResource>
        </testResources>

        <plugins>
            <!-- Generate our MessageCodes class from the *-messages.xml resource file -->
            <plugin>
                <groupId>info.freelibrary</groupId>
                <artifactId>freelib-maven-plugins</artifactId>

                <configuration>
                    <generatedSourcesDirectory>${project.basedir}/src/main/generated</generatedSourcesDirectory>
                </configuration>

                <executions>
                    <execution>
                        <id>generate-media-types</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate-mediatype</goal>
                        </goals>
                        <configuration>
                            <mediaTypePackage>info.freelibrary.iiif.presentation.v3.properties</mediaTypePackage>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <artifactId>maven-javadoc-plugin</artifactId>
                <configuration>
                    <excludePackageNames>
                        info.freelibrary.iiif.presentation.v3.utils.csv:info.freelibrary.iiif.presentation.v3.utils.cmdline
                    </excludePackageNames>
                    <links>
                        <link>https://javadoc.io/doc/info.freelibrary/freelib-utils/${freelib.utils.version}/</link>
                    </links>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
            </plugin>

            <plugin>
                <artifactId>maven-pmd-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>**/info/freelibrary/iiif/presentation/v3/utils/csv/*.java</exclude>
                        <exclude>**/info/freelibrary/iiif/presentation/v3/utils/cmdline/*.java</exclude>
                    </excludes>
                </configuration>
            </plugin>

            <plugin>
                <artifactId>maven-checkstyle-plugin</artifactId>
            </plugin>

            <plugin>
                <artifactId>maven-enforcer-plugin</artifactId>
            </plugin>

            <plugin>
                <artifactId>maven-dependency-plugin</artifactId>
            </plugin>

            <!-- The rules need to be updated to fit some IDEA changes -->
            <plugin>
                <groupId>net.revelc.code.formatter</groupId>
                <artifactId>formatter-maven-plugin</artifactId>
            </plugin>

            <plugin>
                <artifactId>maven-resources-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <configuration>
                    <systemPropertyVariables>
                        <jiiify.version>${project.version}</jiiify.version>
                    </systemPropertyVariables>
                    <argLine><![CDATA[
                        --add-opens java.base/sun.nio.ch=ALL-UNNAMED
                        --add-opens java.base/java.io=ALL-UNNAMED
                        --enable-native-access=ALL-UNNAMED
                    ]]></argLine>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <executions>
                    <execution>
                        <id>default-compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <!-- Exclude the CSV utils from the main compilation process -->
                            <excludes>
                                <exclude>**/info/freelibrary/iiif/presentation/v3/utils/csv/*.java</exclude>
                                <exclude>**/info/freelibrary/iiif/presentation/v3/utils/cmdline/*.java</exclude>
                            </excludes>
                        </configuration>
                    </execution>
                    <execution>
                        <id>default-testCompile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>testCompile</goal>
                        </goals>
                        <configuration>
                            <testExcludes>
                                <!-- Exclude test sources associated with the excluded CSV utils -->
                                <testExclude>**/info/freelibrary/iiif/presentation/v3/utils/csv/*.java</testExclude>
                                <testExclude>**/info/freelibrary/iiif/presentation/v3/utils/cmdline/*.java</testExclude>
                            </testExcludes>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <!-- Uses 'add-opens' argument for system-lambda functionality in unit tests -->
                    <argLine><![CDATA[ ${jacoco.agent.arg} ${mockito.agent.arg}
                        --add-opens java.base/java.util=ALL-UNNAMED
                        --add-opens=java.base/java.lang=ALL-UNNAMED
                        --enable-native-access=ALL-UNNAMED
                    ]]></argLine>
                    <forkCount>1</forkCount>
                    <reuseForks>false</reuseForks>
                    <environmentVariables>
                        <JPV3_HOST>https://iiif.library.ucla.edu</JPV3_HOST>
                    </environmentVariables>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>native</id>

            <properties>
                <!-- Transitive dependencies that are only used in the 'native' build -->
                <kotlin.version>2.2.10</kotlin.version>
                <guava.version>33.4.8-jre</guava.version>
                <picocli.version>4.7.7</picocli.version>
                <mapdb.version>3.1.0</mapdb.version>
                <jsonpath.version>0.6.2</jsonpath.version>

                <graalvm.agent.arg>
                    ${project.basedir}/target/classes/META-INF/native-image/${project.groupId}/${project.artifactId}/
                </graalvm.agent.arg>
                <build.profile>native</build.profile>
                <native.image.agent>true</native.image.agent>

                <!-- Default is the most basic; other options: 'x86-64-v2' or 'armv8-a' or 'native' -->
                <build.arch>compatibility</build.arch>
            </properties>

            <dependencies>
                <dependency>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-classic</artifactId>
                    <scope>compile</scope>
                </dependency>
                <dependency>
                    <groupId>info.picocli</groupId>
                    <artifactId>picocli</artifactId>
                    <version>${picocli.version}</version>
                </dependency>
                <dependency>
                    <groupId>org.mapdb</groupId>
                    <artifactId>mapdb</artifactId>
                    <version>${mapdb.version}</version>
                    <exclusions>
                        <!-- Exclude transitive Kotlin stdlib SNAPSHOT (replace with the stable version below) -->
                        <exclusion>
                            <groupId>org.jetbrains.kotlin</groupId>
                            <artifactId>kotlin-stdlib</artifactId>
                        </exclusion>
                        <!-- Exclude transitive Guava SNAPSHOT (replace with the stable version below) -->
                        <exclusion>
                            <groupId>com.google.guava</groupId>
                            <artifactId>guava</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                <dependency>
                    <groupId>org.jetbrains.kotlin</groupId>
                    <artifactId>kotlin-stdlib</artifactId>
                    <version>${kotlin.version}</version>
                </dependency>
                <dependency>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava</artifactId>
                    <version>${guava.version}</version>
                </dependency>
                <dependency>
                    <groupId>io.github.vishwakarma</groupId>
                    <artifactId>zjsonpatch</artifactId>
                    <version>${jsonpath.version}</version>
                </dependency>
            </dependencies>

            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-enforcer-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>enforce</id>
                                <goals>
                                    <goal>enforce</goal>
                                </goals>
                                <configuration>
                                    <rules combine.self="override">
                                        <requireJavaVersion>
                                            <version>[25,)</version>
                                        </requireJavaVersion>
                                    </rules>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>

                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>default-compile</id>
                                <phase>compile</phase>
                                <goals>
                                    <goal>compile</goal>
                                </goals>
                                <configuration>
                                    <!-- Clear any inherited excludes for native -->
                                    <excludes combine.self="override"/>
                                    <annotationProcessorPaths>
                                        <path>
                                            <groupId>info.picocli</groupId>
                                            <artifactId>picocli-codegen</artifactId>
                                            <version>${picocli.version}</version>
                                        </path>
                                    </annotationProcessorPaths>
                                    <compilerArgs>
                                        <arg>-Aproject=${project.groupId}/${project.artifactId}</arg>
                                    </compilerArgs>
                                </configuration>
                            </execution>
                            <execution>
                                <id>default-testCompile</id>
                                <phase>test-compile</phase>
                                <goals>
                                    <goal>testCompile</goal>
                                </goals>
                                <configuration>
                                    <testExcludes combine.self="override"/>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>

                    <plugin>
                        <groupId>org.graalvm.buildtools</groupId>
                        <artifactId>native-maven-plugin</artifactId>
                        <version>${native.maven.plugin.version}</version>
                        <extensions>true</extensions>
                        <executions>
                            <execution>
                                <id>build-native</id>
                                <goals>
                                    <goal>compile-no-fork</goal>
                                </goals>
                                <phase>package</phase>
                            </execution>
                        </executions>
                        <configuration>
                            <agent>true</agent>
                            <mainClass>info.freelibrary.iiif.presentation.v3.utils.cmdline.JPv3</mainClass>
                            <imageName>jpv3</imageName>
                            <buildArgs>
                                <!--<arg>-Os</arg>--><!-- small size for containers -->
                                <arg>-O3</arg><!-- optimized for desktop -->
                                <arg>-march=${build.arch}</arg>
                                <!--<buildArg>-/-gc=G1</buildArg>--><!-- Adds 20 MB for GC addition -->
                                <!--<arg>-\-exact-reachability-metadata</arg>-->
                                <arg>--enable-native-access=ALL-UNNAMED</arg>
                                <arg>--enable-url-protocols=https</arg>
                                <arg>-H:-ReduceImplicitExceptionStackTraceInformation</arg><!-- For debugging -->
                            </buildArgs>
                            <metadataRepository>
                                <enabled>true</enabled>
                            </metadataRepository>
                        </configuration>
                    </plugin>

                    <plugin>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <systemPropertyVariables>
                                <native.image.agent>true</native.image.agent>
                            </systemPropertyVariables>
                            <argLine><![CDATA[ ${jacoco.agent.arg} ${mockito.agent.arg}
                              -agentlib:native-image-agent=config-merge-dir=${graalvm.agent.arg}
                              --add-opens java.base/java.util=ALL-UNNAMED
                              --add-opens=java.base/java.lang=ALL-UNNAMED
                              --enable-native-access=ALL-UNNAMED
                            ]]></argLine>
                        </configuration>
                    </plugin>

                    <plugin>
                        <artifactId>maven-pmd-plugin</artifactId>
                        <configuration>
                            <excludes combine.self="override"/>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>uber</id>
            <properties>
                <shade.plugin.version>3.6.1</shade.plugin.version>

                <shade.includer>org.apache.maven.plugins.shade.resource.IncludeResourceTransformer</shade.includer>
                <shade.manifest>org.apache.maven.plugins.shade.resource.ManifestResourceTransformer</shade.manifest>
            </properties>
            <dependencies>
                <dependency>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-classic</artifactId>
                    <scope>compile</scope>
                </dependency>
            </dependencies>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-shade-plugin</artifactId>
                        <version>${shade.plugin.version}</version>
                        <executions>
                            <execution>
                                <id>uber-jar</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>shade</goal>
                                </goals>
                                <configuration>
                                    <shadedArtifactAttached>true</shadedArtifactAttached>
                                    <shadedClassifierName>uber</shadedClassifierName>
                                    <filters>
                                        <filter>
                                            <artifact>*:*</artifact>
                                            <excludes>
                                                <exclude>logback.xml</exclude>
                                                <exclude>module-info.class</exclude>
                                                <exclude>META-INF/*.SF</exclude>
                                                <exclude>META-INF/*.DSA</exclude>
                                                <exclude>META-INF/*.RSA</exclude>
                                                <exclude>META-INF/NOTICE</exclude>
                                                <exclude>META-INF/LICENSE</exclude>
                                                <exclude>META-INF/LICENSE.txt</exclude>
                                                <exclude>META-INF/MANIFEST.MF</exclude>
                                                <exclude>META-INF/versions/9/module-info.class</exclude>
                                            </excludes>
                                        </filter>
                                        <filter>
                                            <artifact>com.fasterxml.jackson.dataformat:jackson-dataformat-csv</artifact>
                                            <excludes>
                                                <exclude>META-INF/services/com.fasterxml.jackson.core.ObjectCodec
                                                </exclude>
                                                <exclude>META-INF/services/com.fasterxml.jackson.core.JsonFactory
                                                </exclude>
                                            </excludes>
                                        </filter>
                                    </filters>
                                    <transformers>
                                        <transformer implementation="${shade.includer}">
                                            <resource>logback.xml</resource>
                                            <file>src/test/resources/logback-uber.xml</file>
                                        </transformer>
                                        <transformer implementation="${shade.manifest}">
                                            <mainClass>info.freelibrary.iiif.presentation.v3.utils.cmdline.JPv3</mainClass>
                                        </transformer>
                                    </transformers>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <distributionManagement>
        <snapshotRepository>
            <id>github</id>
            <url>https://maven.pkg.github.com/freelibrary/jiiify-presentation</url>
        </snapshotRepository>
    </distributionManagement>

    <!-- Pulls in standard FreeLibrary Project configuration options -->
    <parent>
        <artifactId>freelib-parent</artifactId>
        <groupId>info.freelibrary</groupId>
        <version>14.0.4</version>
    </parent>

</project>
