# use the setting below to set multiple docs directories.
docSections = ["docs", "tutorials"]

uniqueHomePage = true # change to false to add sidebar to homepage

blogDir = "blog" # blog posts related to jpv3

repo = "https://github.com/ksclarke/jiiify-presentation"

time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"

enableDarkMode = false # set to false to disable darkmode by default
defaultLightingMode = "auto" # other possible values: "dark", "light"

codeMaxLines = 20 # sets max number of lines per code block
showLineNumbers = true # adds lines to code blocks

# By default the template will look for icons under the icons directory. In some situations you might wanna change that. edit the line below
# iconsPath = 'icons/'

otherSearchableFields = ["Tags", "Categories", "CustomField"] # As they appear in frontmatter

enableCopyright = true # sets copyright footer

[search]
  on = true
  global = false # turn to `true` to enable global search

[search.algolia]
  enable = false # if false search will default to fusejs
  id = "Q40WQQX84U" # Application ID
  index = "compose" # Index name
  key = "da87401a458102ec6bbd6cc5e5cf8d95" # Search-Only API Key

[logo]
  lightMode = "images/compose.svg"
  darkMode = "images/compose-light.svg"

[source]
  name = "GitHub"
  iconLight = "images/GitHubMarkLight.svg"
  iconDark = "images/GitHubMarkDark.svg"
  url = "https://github.com/ksclarke/jiiify-presentation/tree/v3"

[author]
  name = "Kevin S. Clarke"
  url = "https://github.com/ksclarke"
