---
title: Annotations
---

classDiagram
direction LR

%% Annotations

`Target` o-- Annotation : aggregates

Annotation <|-- AssessingAnnotation : implements
Annotation <|-- BookmarkingAnnotation : implements
Annotation <|-- ClassifyingAnnotation : implements
Annotation <|-- CommentingAnnotation : implements
Annotation <|-- DescribingAnnotation : implements
Annotation <|-- EditingAnnotation : implements
Annotation <|-- HighlightingAnnotation : implements
Annotation <|-- IdentifyingAnnotation : implements
Annotation <|-- LinkingAnnotation : implements
Annotation <|-- ModeratingAnnotation : implements
Annotation <|-- QuestioningAnnotation : implements
Annotation <|-- ReplyingAnnotation : implements
Annotation <|-- TaggingAnnotation : implements

Annotation <|-- PaintingAnnotation : implements
Annotation <|-- SupplementingAnnotation : implements

PaintingAnnotation --|> Resource : implements
SupplementingAnnotation --|> Resource : implements

AssessingAnnotation --|> WebAnnotation : extends
BookmarkingAnnotation --|> WebAnnotation : extends
ClassifyingAnnotation --|> WebAnnotation : extends
CommentingAnnotation --|> WebAnnotation : extends
DescribingAnnotation --|> WebAnnotation : extends
EditingAnnotation --|> WebAnnotation : extends
HighlightingAnnotation --|> WebAnnotation : extends
IdentifyingAnnotation --|> WebAnnotation : extends
LinkingAnnotation --|> WebAnnotation : extends
ModeratingAnnotation --|> WebAnnotation : extends
QuestioningAnnotation --> WebAnnotation : extends
ReplyingAnnotation --|> WebAnnotation : extends
TaggingAnnotation --|> WebAnnotation : extends

class `Target` {

    -mySpecificResource : SpecificResource
    -myURI : String

    +getSpecificResource() Optional~SpecificResource~
    +getURI() String
}

class Annotation~T~ {
    <<Interface>>

    +bodyHasChoice() boolean

    +getBody() List~ContentResource~?~~
    +getID() String
    +getMotivation() String
    +getTarget() Target
    +getTimeMode() Optional~TimeMode~

    +setBody(ContentResource~T~... aResourceArray) Annotation~T~
    +setBody(List~ContentResource~T~~ aResourceList) Annotation~T~
    +setChoice(boolean aChoice) Annotation~T~
    +setID(String aID) Annotation~T~
    +setMotivation(Motivation aMotivation) Annotation~T~
    +setTarget(Target aTarget) Annotation~T~
    +setTimeMode(TimeMode aTimeMode) Annotation~T~
}

class Resource~T~ {
    <<Interface>>

    +getBehaviors() List~Behavior~
    +getHomepages() List~Homepage~
    +getID() String
    +getLabel() Label
    +getMetadata() List~Metadata~
    +getPartsOf() List~PartOf~
    +getProviders() List~Provider~
    +getRenderings() List~Rendering~
    +getRequiredStatement() RequiredStatement
    +getRights() String
    +getSeeAlsoRefs() List~SeeAlso~
    +getServices() List~Service~?~~
    +getSummary() Summary
    +getThumbnails() List~ContentResource~?~~
    +getType() String

    +setBehaviors(Behavior... aBehaviorArray) Resource~T~
    +setBehaviors(List~Behavior~~ aBehaviorList) Resource~T~
    +setHomepages(Homepage... aHomepageArray) Resource~T~
    +setHomepages(List~Homepage~ aHomepageList) Resource~T~
    +setID(String aID) Resource~T~
    +setLabel(Label aLabel) Resource~T~
    +setLabel(String aLabel) Resource~T~
    +setMetadata(Metadata... aMetadataArray) Resource~T~
    +setMetadata(List~Metadata~ aMetadataList) Resource~T~
    +setPartsOfs(PartOf... aPartOfArray) Resource~T~
    +setPartsOfs(List~PartOf~ aPartOfList) Resource~T~
    +setProviders(Provider... aProviderArray) Resource~T~
    +setProviders(List~Provider~ aProviderList) Resource~T~
    +setRenderings(Rendering... aRenderingArray) Resource~T~
    +setRenderings(List~Rendering~ aRenderingList) Resource~T~
    +setRequiredStatement(RequiredStatement aStatement) Resource~T~
    +setRights(String aRights) Resource~T~
    +setSeeAlsoRefs(SeeAlso... aSeeAlsoArray) Resource~T~
    +setSeeAlsoRefs(List~SeeAlso~ aSeeAlsoList) Resource~T~
    +setServices(Service~?~ aServiceArray) Resource~T~
    +setServices(List~Service~?~~ aServiceList) Resource~T~
    +setSummary(String aSummary) Resource~T~
    +setSummary(Summary aSummary) Resource~T~
    +setThumbnails(ContentResource~?~... aThumbnailArray) Resource~T~
    +setThumbnails(List~ContentResource~?~~ aThumbnailList) Resource~T~
}

class WebAnnotation {

    -myBodyHasChoice : boolean
    -myID : String
    -myLabel : Label
    -myMotivation : String
    -myResources : List~ContentResource~?~~
    -myTarget : Target
    -myTimeMode : TimeMode

    +bodyHasChoice() boolean

    +getBody() List~ContentResource~?~~
    +getID() String
    +getLabel() Optional~Label~
    +getMotication() String
    +getTarget() Target
    +getTimeMode() Optional~TimeMode~

    +setBody(ContentResource~?~... aResourceArray) WebAnnotation
    +setBody(List~ContentResource~?~~ aResourceList) WebAnnotation
    +setChoice(boolean aChoice) WebAnnotation
    +setID(String aID) WebAnnotation
    +setLabel(String aLabel) WebAnnotation
    +setLabel(Label alabel) WebAnnotation
    +setMotivation(Motivation aMotivation) WebAnnotation
    +setTarget(Target aTarget) WebAnnotation
    +setTimeMode(TimeMode aTimeMode) WebAnnotation

    +toString() String
}

class AssessingAnnotation {

    +bodyHasChoice() boolean

    +getBody() List~ContentResource~?~~
    +getID() String
    +getLabel() Optional~Label~
    +getMotivation() String
    +getTarget() Target
    +getTimeMode() Optional~TimeMode~

    +setBody(ContentResource~?~... aResourceArray) AssessingAnnotation
    +setBody(List~ContentResource~?~~ aResourceList) AssessingAnnotation
    +setChoice(boolean aChoice) AssessingAnnotation
    +setID(String aID) AssessingAnnotation
    +setLabel(String aLabel) AssessingAnnotation
    +setLabel(Label aLabel) AssessingAnnotation
    +setMotivation(Motivation aMotivation) AssessingAnnotation
    +setTarget(Target aTarget) AssessingAnnotation
    +setTimeMode(TimeMode aTimeMode) AssessingAnnotation

    +toString() String
}

class BookmarkingAnnotation {

    +bodyHasChoice() boolean

    +getBody() List~ContentResource~?~~
    +getID() String
    +getLabel() Optional~Label~
    +getMotivation() String
    +getTarget() Target
    +getTimeMode() Optional~TimeMode~

    +setBody(ContentResource~?~... aResourceArray) BookmarkingAnnotation
    +setBody(List~ContentResource~?~~ aResourceList) BookmarkingAnnotation
    +setChoice(boolean aChoice) BookmarkingAnnotation
    +setID(String aID) BookmarkingAnnotation
    +setLabel(String aLabel) BookmarkingAnnotation
    +setLabel(Label aLabel) BookmarkingAnnotation
    +setMotivation(Motivation aMotivation) BookmarkingAnnotation
    +setTarget(Target aTarget) BookmarkingAnnotation
    +setTimeMode(TimeMode aTimeMode) BookmarkingAnnotation

    +toString() String
}

class ClassifyingAnnotation {

    +bodyHasChoice() boolean

    +getBody() List~ContentResource~?~~
    +getID() String
    +getLabel() Optional~Label~
    +getMotivation() String
    +getTarget() Target
    +getTimeMode() Optional~TimeMode~

    +setBody(ContentResource~?~... aResourceArray) ClassifyingAnnotation
    +setBody(List~ContentResource~?~~ aResourceList) ClassifyingAnnotation
    +setChoice(boolean aChoice) ClassifyingAnnotation
    +setID(String aID) ClassifyingAnnotation
    +setLabel(String aLabel) ClassifyingAnnotation
    +setLabel(Label aLabel) ClassifyingAnnotation
    +setMotivation(Motivation aMotivation) ClassifyingAnnotation
    +setTarget(Target aTarget) ClassifyingAnnotation
    +setTimeMode(TimeMode aTimeMode) ClassifyingAnnotation

    +toString() String
}

class CommentingAnnotation {

    +bodyHasChoice() boolean

    +getBody() List~ContentResource~?~~
    +getID() String
    +getLabel() Optional~Label~
    +getMotivation() String
    +getTarget() Target
    +getTimeMode() Optional~TimeMode~

    +setBody(ContentResource~?~... aResourceArray) CommentingAnnotation
    +setBody(List~ContentResource~?~~ aResourceList) CommentingAnnotation
    +setChoice(boolean aChoice) CommentingAnnotation
    +setID(String aID) CommentingAnnotation
    +setLabel(String aLabel) CommentingAnnotation
    +setLabel(Label aLabel) CommentingAnnotation
    +setMotivation(Motivation aMotivation) CommentingAnnotation
    +setTarget(Target aTarget) CommentingAnnotation
    +setTimeMode(TimeMode aTimeMode) CommentingAnnotation

    +toString() String
}

class DescribingAnnotation {

    +bodyHasChoice() boolean

    +getBody() List~ContentResource~?~~
    +getID() String
    +getLabel() Optional~Label~
    +getMotivation() String
    +getTarget() Target
    +getTimeMode() Optional~TimeMode~

    +setBody(ContentResource~?~... aResourceArray) DescribingAnnotation
    +setBody(List~ContentResource~?~~ aResourceList) DescribingAnnotation
    +setChoice(boolean aChoice) DescribingAnnotation
    +setID(String aID) DescribingAnnotation
    +setLabel(String aLabel) DescribingAnnotation
    +setLabel(Label aLabel) DescribingAnnotation
    +setMotivation(Motivation aMotivation) DescribingAnnotation
    +setTarget(Target aTarget) DescribingAnnotation
    +setTimeMode(TimeMode aTimeMode) DescribingAnnotation

    +toString() String
}

class EditingAnnotation {

    +bodyHasChoice() boolean

    +getBody() List~ContentResource~?~~
    +getID() String
    +getLabel() Optional~Label~
    +getMotivation() String
    +getTarget() Target
    +getTimeMode() Optional~TimeMode~

    +setBody(ContentResource~?~... aResourceArray) EditingAnnotation
    +setBody(List~ContentResource~?~~ aResourceList) EditingAnnotation
    +setChoice(boolean aChoice) EditingAnnotation
    +setID(String aID) EditingAnnotation
    +setLabel(String aLabel) EditingAnnotation
    +setLabel(Label aLabel) EditingAnnotation
    +setMotivation(Motivation aMotivation) EditingAnnotation
    +setTarget(Target aTarget) EditingAnnotation
    +setTimeMode(TimeMode aTimeMode) EditingAnnotation

    +toString() String
}

class HighlightingAnnotation {

    +bodyHasChoice() boolean

    +getBody() List~ContentResource~?~~
    +getID() String
    +getLabel() Optional~Label~
    +getMotivation() String
    +getTarget() Target
    +getTimeMode() Optional~TimeMode~

    +setBody(ContentResource~?~... aResourceArray) HighlightingAnnotation
    +setBody(List~ContentResource~?~~ aResourceList) HighlightingAnnotation
    +setChoice(boolean aChoice) HighlightingAnnotation
    +setID(String aID) HighlightingAnnotation
    +setLabel(String aLabel) HighlightingAnnotation
    +setLabel(Label aLabel) HighlightingAnnotation
    +setMotivation(Motivation aMotivation) HighlightingAnnotation
    +setTarget(Target aTarget) HighlightingAnnotation
    +setTimeMode(TimeMode aTimeMode) HighlightingAnnotation

    +toString() String
}

class IdentifyingAnnotation {

    +bodyHasChoice() boolean

    +getBody() List~ContentResource~?~~
    +getID() String
    +getLabel() Optional~Label~
    +getMotivation() String
    +getTarget() Target
    +getTimeMode() Optional~TimeMode~

    +setBody(ContentResource~?~... aResourceArray) IdentifyingAnnotation
    +setBody(List~ContentResource~?~~ aResourceList) IdentifyingAnnotation
    +setChoice(boolean aChoice) IdentifyingAnnotation
    +setID(String aID) IdentifyingAnnotation
    +setLabel(String aLabel) IdentifyingAnnotation
    +setLabel(Label aLabel) IdentifyingAnnotation
    +setMotivation(Motivation aMotivation) IdentifyingAnnotation
    +setTarget(Target aTarget) IdentifyingAnnotation
    +setTimeMode(TimeMode aTimeMode) IdentifyingAnnotation

    +toString() String
}

class LinkingAnnotation {

    +bodyHasChoice() boolean

    +getBody() List~ContentResource~?~~
    +getID() String
    +getLabel() Optional~Label~
    +getMotivation() String
    +getTarget() Target
    +getTimeMode() Optional~TimeMode~

    +setBody(ContentResource~?~... aResourceArray) LinkingAnnotation
    +setBody(List~ContentResource~?~~ aResourceList) LinkingAnnotation
    +setChoice(boolean aChoice) LinkingAnnotation
    +setID(String aID) LinkingAnnotation
    +setLabel(String aLabel) LinkingAnnotation
    +setLabel(Label aLabel) LinkingAnnotation
    +setMotivation(Motivation aMotivation) LinkingAnnotation
    +setTarget(Target aTarget) LinkingAnnotation
    +setTimeMode(TimeMode aTimeMode) LinkingAnnotation

    +toString() String
}

class ModeratingAnnotation {

    +bodyHasChoice() boolean

    +getBody() List~ContentResource~?~~
    +getID() String
    +getLabel() Optional~Label~
    +getMotivation() String
    +getTarget() Target
    +getTimeMode() Optional~TimeMode~

    +setBody(ContentResource~?~... aResourceArray) ModeratingAnnotation
    +setBody(List~ContentResource~?~~ aResourceList) ModeratingAnnotation
    +setChoice(boolean aChoice) ModeratingAnnotation
    +setID(String aID) ModeratingAnnotation
    +setLabel(String aLabel) ModeratingAnnotation
    +setLabel(Label aLabel) ModeratingAnnotation
    +setMotivation(Motivation aMotivation) ModeratingAnnotation
    +setTarget(Target aTarget) ModeratingAnnotation
    +setTimeMode(TimeMode aTimeMode) ModeratingAnnotation

    +toString() String
}

class QuestioningAnnotation {

    +bodyHasChoice() boolean

    +getBody() List~ContentResource~?~~
    +getID() String
    +getLabel() Optional~Label~
    +getMotivation() String
    +getTarget() Target
    +getTimeMode() Optional~TimeMode~

    +setBody(ContentResource~?~... aResourceArray) QuestioningAnnotation
    +setBody(List~ContentResource~?~~ aResourceList) QuestioningAnnotation
    +setChoice(boolean aChoice) QuestioningAnnotation
    +setID(String aID) QuestioningAnnotation
    +setLabel(String aLabel) QuestioningAnnotation
    +setLabel(Label aLabel) QuestioningAnnotation
    +setMotivation(Motivation aMotivation) QuestioningAnnotation
    +setTarget(Target aTarget) QuestioningAnnotation
    +setTimeMode(TimeMode aTimeMode) QuestioningAnnotation

    +toString() String
}

class ReplyingAnnotation {

    +bodyHasChoice() boolean

    +getBody() List~ContentResource~?~~
    +getID() String
    +getLabel() Optional~Label~
    +getMotivation() String
    +getTarget() Target
    +getTimeMode() Optional~TimeMode~

    +setBody(ContentResource~?~... aResourceArray) ReplyingAnnotation
    +setBody(List~ContentResource~?~~ aResourceList) ReplyingAnnotation
    +setChoice(boolean aChoice) ReplyingAnnotation
    +setID(String aID) ReplyingAnnotation
    +setLabel(String aLabel) ReplyingAnnotation
    +setLabel(Label aLabel) ReplyingAnnotation
    +setMotivation(Motivation aMotivation) ReplyingAnnotation
    +setTarget(Target aTarget) ReplyingAnnotation
    +setTimeMode(TimeMode aTimeMode) ReplyingAnnotation

    +toString() String
}

class TaggingAnnotation {

    +bodyHasChoice() boolean

    +getBody() List~ContentResource~?~~
    +getID() String
    +getLabel() Optional~Label~
    +getMotivation() String
    +getTarget() Target
    +getTimeMode() Optional~TimeMode~

    +setBody(ContentResource~?~... aResourceArray) TaggingAnnotation
    +setBody(List~ContentResource~?~~ aResourceList) TaggingAnnotation
    +setChoice(boolean aChoice) TaggingAnnotation
    +setID(String aID) TaggingAnnotation
    +setLabel(String aLabel) TaggingAnnotation
    +setLabel(Label aLabel) TaggingAnnotation
    +setMotivation(Motivation aMotivation) TaggingAnnotation
    +setTarget(Target aTarget) TaggingAnnotation
    +setTimeMode(TimeMode aTimeMode) TaggingAnnotation

    +toString() String
}

class PaintingAnnotation {

    +bodyHasChoice() boolean

    +getBehaviors() List~Behavior~
    +getBody() List~ContentResource~?~~
    +getHomepages() List~Homepage~
    +getID() String
    +getLabel() Label
    +getMetadata() List~Metadata~
    +getMotivation() String
    +getPartsOf() List~PartOf~
    +getProviders() List~Provider~
    +getRenderings() List~Rendering~
    +getRequiredStatement() RequiredStatement
    +getRights() String
    +getSeeAlsoRefs() List~SeeAlso~
    +getServices() List~Service~?~~
    +getSummary() Summary
    +getTarget() Target
    +getThumbnails() List~ContentResource~?~~
    +getTimeMode() Optional~TimeMode~
    +getType() String

    +setBehaviors(Behavior... aBehaviorArray) PaintingAnnotation
    +setBehaviors(List~Behavior~~ aBehaviorList) PaintingAnnotation
    +setBody(ContentResource~?~... aResourceArray) PaintingAnnotation
    +setBody(List~ContentResource~?~~~ aResourceList) PaintingAnnotation
    +setHomepages(Homepage... aHomepageArray) PaintingAnnotation
    +setHomepages(List~Homepage~ aHomepageList) PaintingAnnotation
    +setID(String aID) PaintingAnnotation
    +setLabel(Label aLabel) PaintingAnnotation
    +setLabel(String aLabel) PaintingAnnotation
    +setMetadata(Metadata... aMetadataArray) PaintingAnnotation
    +setMetadata(List~Metadata~ aMetadataList) PaintingAnnotation
    +setMotivation(Motivation aMotivation) PaintingAnnotation
    +setPartsOfs(PartOf... aPartOfArray) PaintingAnnotation
    +setPartsOfs(List~PartOf~ aPartOfList) PaintingAnnotation
    +setProviders(Provider... aProviderArray) PaintingAnnotation
    +setProviders(List~Provider~ aProviderList) PaintingAnnotation
    +setRenderings(Rendering... aRenderingArray) PaintingAnnotation
    +setRenderings(List~Rendering~ aRenderingList) PaintingAnnotation
    +setRequiredStatement(RequiredStatement aStatement) PaintingAnnotation
    +setRights(String aRights) PaintingAnnotation
    +setSeeAlsoRefs(SeeAlso... aSeeAlsoArray) PaintingAnnotation
    +setSeeAlsoRefs(List~SeeAlso~ aSeeAlsoList) PaintingAnnotation
    +setServices(Service~?~ aServiceArray) PaintingAnnotation
    +setServices(List~Service~?~~ aServiceList) PaintingAnnotation
    +setSummary(String aSummary) PaintingAnnotation
    +setSummary(Summary aSumamry) PaintingAnnotation
    +setTarget(Target aTarget) PaintingAnnotation
    +setThumbnails(ContentResource~?~... aThumbnailArray) PaintingAnnotation
    +setThumbnails(List~ContentResource~?~~ aThumbnailList) PaintingAnnotation
    +setTimeMode(TimeMode aTimeMode) PaintingAnnotation
}

class SupplementingAnnotation {

    +bodyHasChoice() boolean

    +getBehaviors() List~Behavior~
    +getBody() List~ContentResource~?~~
    +getHomepages() List~Homepage~
    +getID() String
    +getLabel() Label
    +getMetadata() List~Metadata~
    +getMotivation() String
    +getPartsOf() List~PartOf~
    +getProviders() List~Provider~
    +getRenderings() List~Rendering~
    +getRequiredStatement() RequiredStatement
    +getRights() String
    +getSeeAlsoRefs() List~SeeAlso~
    +getServices() List~Service~?~~
    +getSummary() Summary
    +getTarget() Target
    +getThumbnails() List~ContentResource~?~~
    +getTimeMode() Optional~TimeMode~
    +getType() String

    +setBehaviors(Behavior... aBehaviorArray) SupplementingAnnotation
    +setBehaviors(List~Behavior~~ aBehaviorList) SupplementingAnnotation
    +setBody(ContentResource~?~... aResourceArray) SupplementingAnnotation
    +setBody(List~ContentResource~?~~~ aResourceList) SupplementingAnnotation
    +setHomepages(Homepage... aHomepageArray) SupplementingAnnotation
    +setHomepages(List~Homepage~ aHomepageList) SupplementingAnnotation
    +setID(String aID) SupplementingAnnotation
    +setLabel(Label aLabel) SupplementingAnnotation
    +setLabel(String aLabel) SupplementingAnnotation
    +setMetadata(Metadata... aMetadataArray) SupplementingAnnotation
    +setMetadata(List~Metadata~ aMetadataList) SupplementingAnnotation
    +setMotivation(Motivation aMotivation) SupplementingAnnotation
    +setPartsOfs(PartOf... aPartOfArray) SupplementingAnnotation
    +setPartsOfs(List~PartOf~ aPartOfList) SupplementingAnnotation
    +setProviders(Provider... aProviderArray) SupplementingAnnotation
    +setProviders(List~Provider~ aProviderList) SupplementingAnnotation
    +setRenderings(Rendering... aRenderingArray) SupplementingAnnotation
    +setRenderings(List~Rendering~ aRenderingList) SupplementingAnnotation
    +setRequiredStatement(RequiredStatement aStatement) SupplementingAnnotation
    +setRights(String aRights) SupplementingAnnotation
    +setSeeAlsoRefs(SeeAlso... aSeeAlsoArray) SupplementingAnnotation
    +setSeeAlsoRefs(List~SeeAlso~ aSeeAlsoList) SupplementingAnnotation
    +setServices(Service~?~ aServiceArray) SupplementingAnnotation
    +setServices(List~Service~?~~ aServiceList) SupplementingAnnotation
    +setSummary(String aSummary) SupplementingAnnotation
    +setSummary(Summary aSummary) SupplementingAnnotation
    +setTarget(Target aTarget) SupplementingAnnotation
    +setThumbnails(ContentResource~?~... aThumbnailArray) SupplementingAnnotation
    +setThumbnails(List~ContentResource~?~~ aThumbnailList) SupplementingAnnotation
    +setTimeMode(TimeMode aTimeMode) SupplementingAnnotation
}
