---
title: The Services Package
---

classDiagram
direction TD

%% Services

Service <|-- ImageService : extends
Service <|-- OtherService : extends
Service <|-- PhysicalDimsService : implements
Service <|-- AuthTokenService1 : implements
Service <|-- AuthCookieService : extends

ImageService <|-- ImageService2 : implements
ImageService <|-- ImageService3 : implements

OtherService <|-- OtherService2 : implements
OtherService <|-- OtherService3 : implements

AuthCookieService <|-- ExternalCookieService1 : implements
AuthCookieService <|-- KioskCookieService1 : implements
AuthCookieService <|-- UserMediatedCookieService : extends

UserMediatedCookieService <|-- LoginCookieService1 : implements
UserMediatedCookieService <|-- ClickthroughCookieService1 : implements

class Service {
    <<Interface>>

    +getID() String
    +getType() String
    +getProfile() Optional~Service.Profile~
    +getServices() List~Service~?~~

    +setID(String aID) T
    +setType(String aID) T
    +setServices(List~Service~?~~ aServiceList) T
    +setServices(Service~?~... aServiceArray) T
}

class AuthCookieService {
    <<Interface>>

    +getFailureHeader() String
    +getFailureDescription() String

    +setFailureHeader(String aFailureHeader) T
    +setFailureDescription(String aFailureDescription) T
}

class UserMediatedCookieService {
    <<Interface>>

    +getConfirmLabel() String
    +getDescription() String
    +getHeader() String
    +getLabel() String

    +setConfirmLabel(String aLabel) UserMediatedCookieService~T~
    +setDescription(String aDescription) UserMediatedService~T~
    +setHeader(String aHeader) UserMediatedCookieService~T~
    +setLabel(String aLabel) UserMediatedCookieService~T~
}

class ImageService {
    <<Interface>>

    +getExtraFormats() List~ImageAPI.ImageFormat~
    +getExtraQualities() List~ImageAPI.ImageFormat~
    +getProtocol() Optional~String~
    +getTiles() List~Tile~
    +getSizes() List~Size~

    +setExtraFormats(List~ImageAPI.ImageFormat~ aFormatList) T
    +setExtraFormats(ImageAPI.ImageFormat... aFormatArray) T
    +setExtraQualities(List~ImageAPI.ImageQuality~ aQualityList) T
    +setExtraQualities(ImageAPI.ImageQuality... aQualityArray) T
    +setProtocol(boolean aSetValue) T
    +setTiles(List~Tile~ aTileList) T
    +setTiles(Tile... aTileArray) T
    +setSizes(List~Size~ aSizeList) T
    +setSizes(Size... aSizeArray) T
}

class OtherService {
    <<Interface>>

    +getFormat() Optional~MediaType~
    +setFormat(MediaType aMediaType) T
}

class ImageService2 {
    +getID() String
    +getType() String
    +getProfile() Optional~Service.Profile~
    +getServices() List~Service~?~~
    +getExtraFormats() List~ImageAPI.ImageFormat~
    +getExtraQualities() List~ImageAPI.ImageFormat~
    +getProtocol() Optional~String~
    +getTiles() List~Tile~
    +getSizes() List~Size~

    +setID(String aID) T
    +setType(String aID) T
    +setServices(List~Service~?~~ aServiceList) T
    +setServices(Service~?~... aServiceArray) T
    +setExtraFormats(List~ImageAPI.ImageFormat~ aFormatList) T
    +setExtraFormats(ImageAPI.ImageFormat... aFormatArray) T
    +setExtraQualities(List~ImageAPI.ImageQuality~ aQualityList) T
    +setExtraQualities(ImageAPI.ImageQuality... aQualityArray) T
    +setProtocol(boolean aSetValue) T
    +setTiles(List~Tile~ aTileList) T
    +setTiles(Tile... aTileArray) T
    +setSizes(List~Size~ aSizeList) T
    +setSizes(Size... aSizeArray) T

    +toString() String  # Returns a JSON string serialization of the service
}

class ImageService3 {
    +getID() String
    +getType() String
    +getProfile() Optional~Service.Profile~
    +getServices() List~Service~?~~
    +getExtraFormats() List~ImageAPI.ImageFormat~
    +getExtraQualities() List~ImageAPI.ImageFormat~
    +getProtocol() Optional~String~
    +getTiles() List~Tile~
    +getSizes() List~Size~

    +setID(String aID) T
    +setType(String aID) T
    +setServices(List~Service~?~~ aServiceList) T
    +setServices(Service~?~... aServiceArray) T
    +setExtraFormats(List~ImageAPI.ImageFormat~ aFormatList) T
    +setExtraFormats(ImageAPI.ImageFormat... aFormatArray) T
    +setExtraQualities(List~ImageAPI.ImageQuality~ aQualityList) T
    +setExtraQualities(ImageAPI.ImageQuality... aQualityArray) T
    +setProtocol(boolean aSetValue) T
    +setTiles(List~Tile~ aTileList) T
    +setTiles(Tile... aTileArray) T
    +setSizes(List~Size~ aSizeList) T
    +setSizes(Size... aSizeArray) T

    +toString() String  # Returns a JSON string serialization of the service
}

%% JsonKeys defined on methods are overrides
class OtherService2 {
    +getFormat() Optional~MediaType~
    +getID() String # JsonKeys.V2_ID
    +getProfile() Optional~Service.Profile~
    +getServices() List~Service~?~~
    +getType() String # JsonKeys.V2_TYPE

    +setFormat(MediaType aFormat) OtherService2
    +setID(String aID) OtherService2 # JsonKeys.V2_ID
    +setServices(List~Service~?~~ aServiceList) OtherService2
    +setServices(Service~?~... aServiceArray) OtherService2
    +setType(String aType) OtherService2 # JsonKeys.V2_TYPE
}


class OtherService3 {
    +getFormat() Optional~MediaType~
    +getID() String
    +getProfile() Optional~Service.Profile~
    +getServices() List~Service~?~~
    +getType() String

    +setFormat(MediaType aFormat) OtherService3
    +setID(String aID) OtherService3
    +setServices(List~Service~?~~ aServiceList) OtherService3
    +setServices(Service~?~... aServiceArray) OtherService3
    +setType(String aType) OtherService3
}

ImageService2 --|> AbstractImageService : extends
ImageService3 --|> AbstractImageService : extends

OtherService2 --|> AbstractOtherService : extends
OtherService3 --|> AbstractOtherService : extends

ExternalCookieService1 --|> AbstractCookieService : extends
KioskCookieService1 --|> AbstractCookieService : extends
LoginCookieService1 --|> AbstractUserMediatedService : extends
ClickthroughCookieService1 --|> AbstractUserMediatedService : extends

PhysicalDimsService --|> AbstractService : extends
AuthTokenService1 --|> AbstractService : extends
AbstractImageService --|> AbstractService : extends
AbstractOtherService --|> AbstractService : extends
AbstractCookieService --|> AbstractService : extends
AbstractUserMediatedService --|> AbstractCookieService : extends

%% JsonKeys defined on methods instead of fields because they may be overridden
class AbstractService {
    <<Abstract>>

    -myType : String
    -myID : String
    -myProfile : Service.Profile
    -myServices : ~List~Service.Profile~~

    +toString() String  # Returns a JSON string serialization of the service

    #getID() String # JsonKeys.ID
    #getProfile() Optional~Service.Profile~ # JsonKeys.Profile
    #getServices() List~Service~?~~ # JsonKeys.SERVICE
    #getType() String # JsonKeys.TYPE

    #setID(String aID) AbstractService~T~ # JsonKeys.ID
    #setServices(List~Service~?~~ aServiceList) AbstractService~T~ # JsonKeys.SERVICE
    #setServices(Service~?~... aServiceArray) AbstractService~T~ # JsonIgnore
    #setType(String aType) AbstractService~T~ # JsonKeys.TYPE
}

class AbstractImageService {
    <<Abstract>>

    -myFormats : List~ImageAPI.ImageFormat~ # ImageAPI.EXTRA_FORMATS
    -myQualities : List~ImageAPI.ImageQuality~ # ImageAPI.EXTRA_QUALITIES
    -myTiles : List~Tile~ # ImageAPI.TILES
    -mySizes : List~Size~ # ImageAPI.SIZES
    -myProtocolIsSet : boolean

    #getExtraFormats() List~Format~
    #getExtraQualities() List~Quality~
    #getProtocol() Optional~String~ # ImageAPI.PROTOCOL
    #getSizes() List~Size~
    #getTiles() List~Tile~

    #setExtraFormats(Format... aFormatArray) AbstractImageService~T~
    #setExtraFormats(List~Format~ aFormatList) AbstractImageService~T~
    #setExtraQualities(Quality... aQualityArray) AbstractImageService~T~
    #setExtraQualities(List~Quality~ aQualityList) AbstractImageService~T~
    #setProtocol(boolean aSetValue) AbstractImageService~T~ # JsonIgnore
    #setSizes(Size... aSizeArray) AbstractImageService~T~
    #setSizes(List~Size~ aSizeList) AbstractImageService~T~
    #setTiles(Tile... aTileArray) AbstractImageService~T~
    #setTiles(List~Tile~ aTileList) AbstractImageService~T~
}

class AbstractOtherService {
    <<Abstract>>

    -myFormat : MediaType # JsonKeys.FORMAT

    #getFormat() Optional~MediaType~
    #setFormat(MediaType aFormat) AbstractOtherService~T~ 
}

%% JsonKeys defined on methods are overrides
class AbstractCookieService {
    <<Abstract>>

    -myFailureDescription : String # JsonKeys.FAILURE_DESCRIPTION
    -myFailureHeader : String # JsonKeys.FAILURE_HEADER

    #getContext() String # JsonKeys.CONTEXT
    #getFailureDescription() String
    #getFailureHeader() String
    #getID() String # JsonKeys.V2_ID
    #getType() String # JsonKeys.V2_TYPE

    #setFailureDescription(String aFailureDescription) AbstractCookieService~T~
    #setFailureHeader(String aFailureHeader) AbstractCookieService~T~
    #setID(String aID) AbstractCookieService~T~ # JsonKeys.V2_ID
    #setType(String aType) AbstractCookieService~T~ # JsonKeys.V2_TYPE
}

class AbstractUserMediatedService {
    <<Abstract>>

    -myLabel : String # JsonKeys.LABEL
    -myConfirmLabel : String # JsonKeys.CONFIRM_LABEL
    -myHeader : String # JsonKeys.HEADER
    -myDescription : String # JsonKeys.DESCRIPTION

    #getLabel() String
    #getConfirmLabel() String
    #getHeader() String
    #getDescription() String

    #setLabel(String aLabel) UserMediatedCookieService~T~
    #setConfirmLabel(String aLabel) UserMediatedCookieService~T~
    #setHeader(String aHeader) UserMediatedCookieService~T~
    #setDescription(String aDescription) UserMediatedCookieService~T~
}

class ExternalCookieService1 {
    +getFailureDescription() String
    +getFailureHeader() String
    +getID() String
    +getProfile() Optional~Service.Profile~
    +getServices() List~Service~?~~
    +getType() String

    +setFailureDescription(String aFailureDescription) ExternalCookieService1
    +setFailureHeader(String aFailureHeader) ExternalCookieService1
    +setID(String aID) ExternalCookieService1
    +setServices(List~Service~?~~ aServiceList) ExternalCookieService1
    +setServices(Service~?~... aServiceArray) ExternalCookieService1
    +setType(String aType) ExternalCookieService1

    +toString() String  # Returns a JSON string serialization of the service
}

class KioskCookieService1 {
    +getFailureDescription() String
    +getFailureHeader() String
    +getID() String
    +getProfile() Optional~Service.Profile~
    +getServices() List~Service~?~~
    +getType() String

    +setFailureDescription(String aFailureDescription) KioskCookieService1
    +setFailureHeader(String aFailureHeader) KioskCookieService1
    +setID(String aID) KioskCookieService1
    +setServices(List~Service~?~~ aServiceList) KioskCookieService1
    +setServices(Service~?~... aServiceArray) KioskCookieService1
    +setType(String aType) KioskCookieService1

    +toString() String  # Returns a JSON string serialization of the service
}

class ClickthroughCookieService1 {
    +getConfirmLabel() String
    +getDescription() String
    +getFailureDescription() String
    +getFailureHeader() String
    +getHeader() String
    +getID() String
    +getLabel() String
    +getProfile() Optional~Service.Profile~
    +getServices() List~Service~?~~
    +getType() String

    +setConfirmLabel(String aLabel) ClickthroughCookieService1
    +setDescription(String aDescription) ClickthroughCookieService1
    +setFailureDescription(String aFailureDescription) ClickthroughCookieService1
    +setFailureHeader(String aFailureHeader) ClickthroughCookieService1
    +setHeader(String aHeader) ClickthroughCookieService1
    +setID(String aID) ClickthroughCookieService1
    +setLabel(String aLabel) ClickthroughCookieService1
    +setServices(List~Service~?~~ aServiceList) ClickthroughCookieService1
    +setServices(Service~?~... aServiceArray) ClickthroughCookieService1
    +setType(String aType) ClickthroughCookieService1

    +toString() String  # Returns a JSON string serialization of the service
}

class LoginCookieService1 {
    +getConfirmLabel() String
    +getDescription() String
    +getFailureDescription() String
    +getFailureHeader() String
    +getHeader() String
    +getID() String
    +getLabel() String
    +getProfile() Optional~Service.Profile~
    +getServices() List~Service~?~~
    +getType() String

    +setConfirmLabel(String aLabel) LoginCookieService1
    +setDescription(String aDescription) LoginCookieService1
    +setFailureDescription(String aFailureDescription) LoginCookieService1
    +setFailureHeader(String aFailureHeader) LoginCookieService1
    +setHeader(String aHeader) LoginCookieService1
    +setID(String aID) LoginCookieService1
    +setLabel(String aLabel) LoginCookieService1
    +setServices(List~Service~?~~ aServiceList) LoginCookieService1
    +setServices(Service~?~... aServiceArray) LoginCookieService1
    +setType(String aType) LoginCookieService1

    +toString() String  # Returns a JSON string serialization of the service
}

%% One method's (de)serialization ignored; the rest inherited or defined on fields
class PhysicalDimsService {
    -myPhysicalScale : double # JsonKeys.PHYSICAL_SCALE
    -myPhysicalUnits : String # JsonKeys.PHYSICAL_UNITS

    +getID() String
    +getPhysicalScale() double
    +getPhysicalUnits() String
    +getProfile() Optional~Service.Profile~
    +getServices() List~Service~?~~
    +getType() String

    +setDims(double aPhysicalScale, String aPhysicalUnits) PhysicalDimsService # JsonIgnore
    +setID(String aID) PhysicalDimsService
    +setPhysicalScale(double aScale) PhysicalDimsService
    +setPhysicalUnits(String aPhysicalUnits) PhysicalDimsService
    +setServices(List~Service~?~~ aServiceList) PhysicalDimsService
    +setServices(Service~?~ aServiceArray) aPhysicalDimsService
    +setType(String aType) aPhysicalDimsService

    +toString() String  # Returns a JSON string serialization of the service
}

%% JsonKeys defined on methods are overrides
class AuthTokenService1 {
    +getID() String # JsonKeys.V2_ID
    +getProfile() Optional~Service.Profile~
    +getServices() List~Service~?~~
    +getType() String # JsonKeys.V2_TYPE

    +setID(String aID) AuthTokenService1 # JsonKeys.V2_ID
    +setServices(List~Service~?~~ aServiceList) AuthTokenService1
    +setServices(Service~?~... aServiceArray) AuthTokenService1
    +setType(String aType) AuthTokenService1 # JsonKeys.V2_TYPE

    +toString() String  # Returns a JSON string serialization of the service
}
