#! /bin/bash

#
# Gets the next stable version from a Maven snapshot project.
#

VERSION=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec)
PROJECT=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.artifactId}' --non-recursive exec:exec)

echo $PROJECT-${VERSION%"-SNAPSHOT"}
