# Nightly JVM build (not the native build)
name: Nightly JVM Build

# We require all commits to go through PR on GitHub
on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * *'

jobs:
  build:
    name: Maven PR Builder (JDK ${{ matrix.java }}, ${{ matrix.os}})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            java: "21"
            graalvm: "24"
            maven: "3.8.6"
            suffix: "linux-x64"
          - os: "macos-latest"
            java: "21"
            graalvm: "24"
            maven: "3.8.6"
            suffix: "macos-x64"
          - os: "windows-latest"
            java: "21"
            graalvm: "24"
            maven: "3.8.6"
            suffix: "windows-x64"

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0  # Unshallow checkout helps SonarCloud provide more info
          ref: develop

      - name: Install GraalVM
        uses: graalvm/setup-graalvm@7a1da54cb7fdef4ea19f6ecdfa9ecf59dc5a48fe # v1.3.6
        with:
          java-version: ${{ matrix.graalvm }}
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'

      # If running locally in ACT, install Maven
      - name: Set up Maven
        uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1 # v5
        with:
          maven-version: ${{ matrix.maven }}

      - name: Cache SonarCloud packages
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build with Maven
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.BUILD_PASSPHRASE }}
          MAVEN_GPG_KEY: ${{ secrets.BUILD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B -ntp -Prelease deploy javadoc:javadoc

