name: PR Auto-Approver

# Auto-approve on projects that have a "secret" variable saying this is okay. This lets us set up a restricted PR
# process on projects with just a single active developer. It prevents the developer from pushing directly to the
# main branch (so enforces a particular workflow that our other GitHub Actions expect).
on:
  pull_request:
    branches:
      - main

jobs:
  approve-pr:
    name: PR Auto-Approver
    runs-on: ubuntu-latest
    env:
      AUTO_PR_APPROVAL: ${{ secrets.AUTO_PR_APPROVAL }}
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      if: env.AUTO_PR_APPROVAL != null
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"