name: Maven Release

# Deploy the webrepl when a new tag is published
on:
  push:
    tags: [ 'webrepl-*' ]

jobs:
  release:
    name: Maven PR Builder (JDK ${{ matrix.java }})
    runs-on: ubuntu-latest
    env:
      AUTORELEASE_ARTIFACT: false
      MAVEN_GPG_PASSPHRASE: ${{ secrets.BUILD_PASSPHRASE }}
      NEXUS_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
    strategy:
      matrix:
        java: [ 21 ]

    steps:

      - name: Check out source code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@860f60056505705214d223b91ed7a30f173f6142 # v3.3.0
        with:
          cache: maven
          distribution: 'adopt'
          java-version: ${{ matrix.java }}

      - name: Login to Docker repository
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set release version
        shell: bash
        run: |
          GITHUB_REF="${{ github.ref }}" &&
          TAG_NAME="${GITHUB_REF#refs/tags/}" &&
          echo "RELEASE_VERSION=${TAG_NAME#webrepl-}" >> $GITHUB_ENV

      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn -B -ntp deploy -Drevision=${{ env.RELEASE_VERSION }} -Prelease \
            -Dgpg.keyname="{{ secrets.BUILD_KEY }} -Dautorelease.artifact=${{ env.AUTORELEASE_ARTIFACT }
