name: Maven Release

# Deploy the webrepl when a new tag is pushed
on:
  push:
    tags: [ 'webrepl-*' ]

jobs:
  release:
    name: Maven PR Builder (JDK ${{ matrix.java }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ 21 ]
        maven: [ 3.8.2 ]
        jdk: [ adopt ]

    steps:
      - name: Check out source code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1
        with:
          buildkitd-flags: --debug

      - name: Login to Docker repository
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@860f60056505705214d223b91ed7a30f173f6142 # v3.3.0
        with:
          cache: maven
          distribution: ${{ matrix.jdk }}
          java-version: ${{ matrix.java }}

      - name: Set release version
        shell: bash
        run: |
          GITHUB_REF="${{ github.ref }}" &&
          TAG_NAME="${GITHUB_REF#refs/tags/}" &&
          echo "RELEASE_VERSION=${TAG_NAME#webrepl-}" >> $GITHUB_ENV

      # If running locally in act, install Maven
      - name: Set up Maven if needed
        if: ${{ env.ACT }}
        uses: stCarolas/setup-maven@07fbbe97d97ef44336b7382563d66743297e442f # v4.5
        with:
          maven-version: ${{ matrix.maven }}

      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.BUILD_PASSPHRASE }}
          MAVEN_GPG_KEY: ${{ secrets.BUILD_KEY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_ACCOUNT: ${{ secrets.DOCKER_ACCOUNT }}
          DOCKER_BUILDKIT: 1
        run: |
          mvn -B -ntp deploy -Prelease -Drevision="${{ env.RELEASE_VERSION }}" -DskipNexusStagingDeployMojo="true"
