name: Maven Release

# Performs a Maven release using JDK 17 when a new GitHub release has been published
on:
  release:
    types: [ published ]

jobs:
  release:
    name: Maven Artifact Publisher (JDK 17)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ "17" ]
        maven: [ "3.8.6" ]
        jdk: [ "temurin" ]

    steps:
      - name: Check out source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          cache: maven
          distribution: ${{ matrix.jdk }}
          java-version: ${{ matrix.java }}
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      # If running locally in ACT, install Maven in the container
      - name: Set up Maven
        uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1 # v5
        if: ${{ env.ACT }}
        with:
          maven-version: ${{ matrix.maven }}

      - name: Set release version
        shell: bash
        run: TAG_NAME="${{ github.event.release.tag_name }}" && echo "RELEASE_VERSION=${TAG_NAME%-*}" >> $GITHUB_ENV

      - name: Release with Maven
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.BUILD_PASSPHRASE }}
          MAVEN_GPG_KEY: ${{ secrets.BUILD_KEY }}
        run: |
          mvn -V -B -ntp deploy -Prelease -DlogLevel=DEBUG -DtestLogLevel=DEBUG -Drevision=${{ env.RELEASE_VERSION }}
